title: CaringBridge Engineering
description: "CaringBridge's software engineering blog."
baseurl: ""
url: "http://caringbridge.github.io"

exclude: ["vendor", ".git", ".gitignore", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown
permalink: pretty

# Frontmatter Defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
    scope:
      path: "css"
      layout: nil

safe: true
timezone: America/Chicago
encoding: utf-8
