title: CaringBridge Engineering
description: "CaringBridge's software engineering blog."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

# Frontmatter Defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
    scope:
      path: "css"
      layout: nil

safe: true
timezone: America/Chicago
encoding: utf-8
sass:
  sass_dir: _sass
